services:
  db:
    image: postgres:15
    container_name: scorefrost-db
    env_file: .env
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDB}
    ports:
      - "${PGPORT}:${PGPORT}"
    volumes:
      - scorefrost-data:/var/lib/postgresql/data

  api:
    container_name: scorefrost-api
    build: .
    env_file: .env
    environment:
      - PGHOST=db
      - DOCKER_ENV=true
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db

  migrate:
    image: migrate/migrate:4
    env_file: .env
    volumes:
      - ./sql/migrations:/migrations:ro
    entrypoint: ["/bin/sh", "-lc"]
    command:
      - >
        migrate
        -path=/migrations
        -database "postgres://${PGUSER}:${PGPASSWORD}@db:${PGPORT}/${PGDB}?sslmode=disable"
        up
    depends_on:
      - db

volumes:
  scorefrost-data:
