### Create a new user
POST {{host}}/api/{{api_version}}/user
Content-Type: application/json

{
	"game_id": "com.hexfrost.test",
  "game_version": "1.0.0-dev+0001"
}

###

### Authenticate an existing user
POST {{host}}/api/{{api_version}}/user
Content-Type: application/json
Authorization: Bearer {{api_key}}

{
	"game_id": "com.hexfrost.test",
  "game_version": "1.0.0-dev+0000"
}

###

### Variables
@host = http://localhost:8080
@api_version = v2
@api_key = key_here
